# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'michisirube' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Apollo"
  pod 'KeychainSwift', '~> 19.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  # Pods for michisirube

  target 'michisirubeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'michisirubeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
