name: michisirube
options:
  bundleIdPrefix: com.icloud.kaitokudou2468110921
targets:
  michisirube:
    type: application
    platform: iOS
    sources: michisirube
    settings:
      CURRENT_PROJECT_VERSION: 1
    prebuildScripts:
    - script: |
        SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
        cd "${SRCROOT}/${TARGET_NAME}"
        "${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
        "${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="https://miraikeitai2020-bff.herokuapp.com/query"
      name: Apollo client